### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by aequitas** [jan4843/docker_stats_exporter#1]
What license is this software?

**Comment by jan4843** [comment]
I didn’t concern myself with it because I published the repository so that I could reference it in my other private projects.

Would there be a use case for you where a license is needed?

**Comment by aequitas** [comment]
I'd like to deploy this as part of an open source project https://github.com/internetstandards/Internet.nl/pull/1142.

**Comment by jan4843** [comment]
I added a license. Let me know if it is incompatible with your needs.

**Comment by aequitas** [comment]
Thanks, MIT will do fine. Also thanks for this project, it's a lot nicer to work with compared to cAdvisory for what I'm using it for.
